
### Is the server on?
get http://localhost:2020/

######## GET calls ########

### Get a list of all the projects
get http://localhost:2020/api/projects

### Get a specific project
get http://localhost:2020/api/projects/2

### Get a list of all the resources
get http://localhost:2020/api/resources

### Get the resources for a project
get http://localhost:2020/api/resources/1

### List all the tasks
get http://localhost:2020/api/tasks

### List the tasks for a project
get http://localhost:2020/api/tasks/1

####### POST calls ########

### Add a task
post http://localhost:2020/api/tasks
content-type: application/json

{
  "project_id": 2,
  "description": "Submit a sprint retro form.",
  "notes": "Don't forget!"
}

### Add a project
post http://localhost:2020/api/projects
content-type: application/json

{
  "name": "Build a wall",
  "description": "This is a sea wall. NOT a border wall."
}

### Add a resource
post http://localhost:2020/api/resources
content-type: application/json

{
  "name": "Clay tablets",
  "description": "In case the printer doesn't work."
}